### PR TITLE
Add link states

### PR DESCRIPTION
**Pull request by NickColley**
Not sure about this one, because the links are styled by a parent theme class all non themed links need  overriding.

Suggestion would be to make classes with lower specificity e.g. .link-green but would require a ton of markup change :cry:

329 B increase in file size:

```
gzip-size src/css/prod/hoodie.min.pref.css | pretty-bytes
6.88 kB -> 7.21 kB
```

### CODE REVIEW

**Comment by varjmes** [comment]
Heya. Could we get some images/.gifs of the on/off (not focused, focused) states? I find it helps other people to review who may not be CSS-confident. Also maybe a little explanation why we want these states? :)

**Comment by varjmes** [comment]
Also, did you check the contrast ratios and such? Not to say you didn't (it's late here, I haven't checked yet), but just want to double check as you said 'subtle' but we don't want them to be too subtle.

**Comment by NickColley** [comment]
Yeah I can try and get the gifs for you, I normally post screenshots for this kind of thing but don't have recording set up at the moment.

In terms of contrast, there's a lot of contrast issues in the site and I think that should be dealt with separately.

The changes here generally darken all the colours with the exception of the white on a dark background.

**Comment by varjmes** [comment]
@nickcolley for .gifs, Licecap ([link](http://www.cockos.com/licecap/)) is great. Small program, makes the .gif, saves the .gif.
If you can't do .gifs, screenshots are defo cool.
I agree that there are contrast issues but if we make sure the link hover/active states are actually noticeable, it's a good start. We don't want to add hover states that we'd have to change all over again. :)

**Comment by NickColley** [comment]
Ended up using byzanz (http://www.unixmen.com/make-animated-gif-screencasts-easily-byzanz/)

**Comment by varjmes** [comment]
I fear these might be a little too subtle. Id need to inspect it a little
more (havebt had a chance to see with my own eyes yet). Though they do look
very cool. I like them. :)

**Comment by NickColley** [comment]
@Charlotteis agree they could be more distinctive, do you want to open this one up for someone else? (Don't like open PRs :P)

**Comment by varjmes** [comment]
I don't think this will be touched until the CSS team finish their work.

**Comment by varjmes** [comment]
@lewiscowper & @verpixelt to confirm tho

**Comment by verpixelt** [comment]
Imho it doesn't make much sense to work on that before the refactoring.

**Comment by NickColley** [comment]
Okay, let me know if you need any help refactoring :+1:

**Pull request closed without merging**
